### ISSUE TITLE
Session not expired

### ISSUE THREAD

**Issue by teamon** [redis-store/redis-rails#10]
Hi,

Is there a way to set redis' EXPIRE when using `:redis_store` as session store? I noticed it's not set by default and the amount of session keys stored in redis keeps growing.

**Comment by joshuawscott** [comment]
You can just pass the `:expire_in` option to the session store.  e.g., from an initializer I do:
```
MyAppName::Application.config.session_store :redis_store, expire_in: 7.days
```

**Comment by jason0415** [comment]
I think it should be "expires_in" instead of "expire_in"

**Comment by radar** [comment]
Correct. I've updated @joshuawscott's comment.
