### ISSUE TITLE
Rails 3 with redis-rails 3.2.4 config

### ISSUE THREAD

**Issue by epochslee** [redis-store/redis-rails#103]
I've set this in config/environments/production.rb, however, it does not pick up on these options but uses the default localhost:6379 host and port. Why does it not pick up on the config?

```
# config/initializers/session_store.rb
MyApplication::Application.config.session_store :redis_store
```

```
In config/environments/production.rb
config.cache_store = :redis_store, {
    host: "ourinternaldomain",
    port: 6336,
    db: 0,
    namespace: "redis-#{Rails.application.class}-#{Rails.env}"
  }, {
    expires_in: 20.minutes
  }
```

I've also tried this below. None of these affect the host and port:
```
# config/application.rb
config.cache_store = :redis_store, 'redis://localhost:6379/0/cache', { expires_in: 90.minutes }
```

When I run console in production mode:
```
$ rails c production
Loading production environment (Rails 3.2.22.5)
2.3.8 :001 > Redis.new
 => #<Redis client v4.1.3 for redis://127.0.0.1:6379/0> 
2.3.8 :002 > 
```

**Comment by tubbo** [comment]
the `Redis` object is not the same as `Redis::Store`. try doing `Rails.cache.data` to see the object that we're using for the cache.

**Comment by epochslee** [comment]
Rails.cache seems to show the right host and port. However, when I deploy it in production, it seems to be using the default host and port still. Is there something incorrect about my configs?

**Comment by tubbo** [comment]
What’s “it”? Are you using the Redis class directly in your app?
  

  
  

  
  
>

**Comment by epochslee** [comment]
No I'm only using it as session_store. I get an error in the log is how I know it's not using the right host and port.

**Comment by tubbo** [comment]
Oh I see what you mean. The session_store must be configured separately, like so:

```ruby
MyApplication::Application.config.session_store :redis_store, servers: ['redis://localhost:6379/0/cache']
```

**Comment by epochslee** [comment]
I'll try it out and will close if it works. Thanks.

**Comment by epochslee** [comment]
That did not work for me. I change it to this in session_store:
```
MyApplication::Application.config.session_store :redis_store, servers: ['redis://localhost:6363/0/cache']
```

But in rails console, I got this:
```
Loading development environment (Rails 3.2.22.5)
2.3.8 :001 > Redis.new
 => #<Redis client v4.1.3 for redis://127.0.0.1:6379/0> 
2.3.8 :002 > 
```

**Comment by tubbo** [comment]
A new instance of `Redis` isn't going to be pre-configured with the settings in `config.session_store`. I believe the store is instantiated in the `ActionDispatch::Session` middleware per request, so it might be difficult to actually get a new instance. With that configuration, are you seeing any sessions being saved? You might also need a `key: '_yourapp_session' if I'm not mistaken...

**Comment by tubbo** [comment]
@epochslee any new updates? gonna close in a few days if not.
