### ISSUE TITLE
SSL Support Available?

### ISSUE THREAD

**Issue by francis-villanueva** [redis-store/redis-rails#104]
I was digging briefly through the code as well as the redis-store repo as well and I was wondering if there is a way to pass SSL certificates to connect to a Redis server that requires it.

For example, when connecting to Redis directly, something like this:

```
ca_file = 'config/ssl/[my-ca-file]'
cert_file = 'config/ssl/[my-cert-file]'
key_file = 'config/ssl/[my-key-file]'
cert_store = OpenSSL::X509::Store.new
cert_store.set_default_paths

redis_options = {
    url: redis_url,
    ssl: true,
    ssl_params: {
      ca_file: ca_file,
      cert: OpenSSL::X509::Certificate.new(File.read(cert_file)),
      key: OpenSSL::PKey::RSA.new(File.read(key_file)),
      cert_store: cert_store
    }
}

Redis.new(redis_options)
```

Is there some current workaround on passing those SSL params in your libraries to when it finally connects with Redis?

Thanks!

**Comment by tubbo** [comment]
We pass all unhandled options to the underlying Redis library, as Redis::Store is a subclass of Redis. Did you try passing those settings in? I feel like they should work in some capacity depending on how you’re instantiating the store.

**Comment by francis-villanueva** [comment]
Yea, I tried a couple things but I couldn't get it to work. Perhaps I was passing in the extra params incorrectly. I was trying to backtrace the entire thing to see how all the options got parsed and eventually to Redis itself.

```
...

ssl_params = {
      ca_file: ca_file,
      cert: OpenSSL::X509::Certificate.new(File.read(cert_file)),
      key: OpenSSL::PKey::RSA.new(File.read(key_file)),
      cert_store: cert_store
    }

Rails.application.config.session_store :redis_store, redis_server: redis_url + '/example_sessions', key: session_key, ssl_params

# OR

Rails.application.config.session_store :redis_store, redis_server: redis_url + '/example_sessions', key: session_key, { ssl_params:  ssl_params }

```

**Comment by tubbo** [comment]
If you're using redis-store for sessions, I think you might need to pass in the options in the `:redis_server` key, like so:

```
Rails.application.config.session_store :redis_store, redis_server: redis_url + '/example_sessions', key: session_key, redis_server: { ssl_params: ssl_params }
```

https://github.com/redis-store/redis-rack/blob/master/lib/redis/rack/connection.rb#L35

**Comment by francis-villanueva** [comment]
Cool. I'll give this a try soon! Thanks!
