### ISSUE TITLE
Recursive Documentation for Rails

### ISSUE THREAD

**Issue by cguess** [redis-store/redis-rails#106]
The documentation here states
> We are still actively maintaining all other gems in the redis-store family, such as redis-actionpack for session management

However, the documentation on `redis-actionpack` says
> For information on how to use this library in a Rails app, see the documentation for redis-rails.

Which doesn't really clean up anything. Would it be possible to clarify these instructions?

I've also opened an issue on the `redis-actionpack` repo here https://github.com/redis-store/redis-actionpack/issues/30

**Comment by tubbo** [comment]
Closing this issue as it's a dupe, we can always transfer redis-store/redis-actionpack#30 here if need be.
