### ISSUE TITLE
Sentinel auth

### ISSUE THREAD

**Issue by dzoniub** [redis-store/redis-rails#107]
Hi,

I haven't found a way to pass password to redis sentinels for authentication. I saw in redis-rb https://github.com/redis/redis-rb#sentinel-support that there's that option, and I tried passing it like that, but it just returns `NOAUTH Authentication required` error. Is this feature added in redis-rails or if not, is there some workaround?

Thanks

**Comment by tubbo** [comment]
Hi @dzoniub! `Redis::Store` is actually a [subclass of `Redis`](https://github.com/redis-store/redis-store/blob/master/lib/redis/store.rb#L13), so you should be able to pass the `sentinels:` option in. Can you show me the code you're using to set this option? Perhaps it's not making it down into the underlying `Redis::Store` object. Most of the gems here are effectively just adapters for the various uses of the underlying store, so I have a hunch if there is a problem, it has to do with one of those libraries not passing down the full set of options when they aren't recognized.

**Comment by dzoniub** [comment]
Hey @tubbo, thanks for such a quick answer, sure here's the code:
```
sentinel_config = {
      url: 'redis://somedbname/1',
      role: 'master',
      sentinels: [
          { host: sentinelhost1, port: 26379, password: 'supersecurepass' },
          { host: sentinelhost2,  port: 26379, password: 'supersecurepass' },
          { host: sentinelhost3,  port: 26379, password: 'supersecurepass' }
      ],
      password: 'supersecurepass',
}

config.cache_store = :redis_store, sentinel_config.merge(
      namespace: 'somedbname'
)
```
So the password inside of sentinels should set password auth for sentinels, and one password below is used for master-replicas redis servers. I've tested with auth turned off on sentinel servers where I only put `requirepass` and `masterauth` on caching servers, and `sentinel auth-pass` on sentinel to authenticate to caching servers, and when I tried to execute it like that from my application, everything was fine, but as soon as I set `requirepass` on sentinel servers, it gives me `NOAUTH ...` error. I've also tried to turn off auth for caching servers, and only put `requirepass` for sentinels, and it's the same story.

**Comment by tubbo** [comment]
Does that same config work by just calling `Redis.new(sentinel_config)`?

**Comment by dzoniub** [comment]
I've tried that just now, and it's still returning `NOAUTH Authentication required.` when i call
```
redis = Redis.new(sentinel_config)
redis.set("somekey", "helloworld")
```

**Comment by dzoniub** [comment]
Ok, so that probably means that my redis-rb is old version which doesn't support sentinel auth. It's 3.3.1, that's a little too old, I'll try updating.

**Comment by dzoniub** [comment]
Yep, that did the trick, sorry for the false alarm.
