### ISSUE TITLE
Question about code samples in readme

### ISSUE THREAD

**Issue by KurtRMueller** [redis-store/redis-rails#13]
Hey guys,

I have a question regarding two code snippets in the readme and figure this would probably be the best place to ask:

In the section, [Usage](https://github.com/redis-store/redis-rails#usage):

In your redis uri, you have the `cache_store` using database 0 on your localhost, but you have `rack_cache`'s `metastore` and `entitystore` using database 1. Is this common practice to utilize different databases for each or is this simply an example?

Thanks for any help!

Kurt

**Comment by tubbo** [comment]
On some hosts, like Heroku, you are limited in the amount of databases on your Redis instance. However, if you run Redis yourself the program will allow you up to 16 of these databases. [mperham wrote a good article about how to use namespaces and databases effectively](http://www.mikeperham.com/2015/09/24/storing-data-with-redis/), essentially saying that databases are kind-of a "poor man's multiple instances", and while having multiple Redis instances configured for different paradigms is the ideal approach, not everyone has that kind of capital to invest. So, databases are a good solution to this problem. I've certainly never had any issues working with multiple databases, always preferring to keep "cache data" (rails/rack cache) and "ephemeral data" (job queue, session) fundamentally separated..
