### ISSUE TITLE
:expires_at option is not working

### ISSUE THREAD

**Issue by sonyshchuk** [redis-store/redis-rails#17]
Hi there,

Is it possible to use expires_at option right now?

Ruby 2.2.0
Rails 4.2.1

redis (3.2.1)
    redis-actionpack (4.0.0)
      actionpack (~> 4)
      redis-rack (~> 1.5.0)
      redis-store (~> 1.1.0)
    redis-activesupport (4.0.0)
      activesupport (~> 4)
      redis-store (~> 1.1.0)
    redis-rack (1.5.0)
      rack (~> 1.5)
      redis-store (~> 1.1.0)
    redis-rails (4.0.0)
      redis-actionpack (~> 4)
      redis-activesupport (~> 4)
      redis-store (~> 1.1.0)
    redis-store (1.1.4)
      redis (>= 2.2)

thanks,

**Comment by radar** [comment]
If it was, would you still be posting this issue?

---

Can you show an example of the usage please?

**Comment by sonyshchuk** [comment]
Nope, this issue wouldn't appear in this case.

I'm wondering if there is any chance to use expires_at config instead of expires_in, like this:
/application.rb
config.cache_store = :redis_store, Rails.application.secrets.redis_url, { expires_at: Time.new.midnight }

**Comment by radar** [comment]
Nope. For that I would recommend using a cron job.
