### ISSUE TITLE
Permit configuration of serializer

### ISSUE THREAD

**Issue by charles-dyfis-net** [redis-store/redis-rails#18]
At present, monkeypatching is necessary to switch from Marshall to JSON.

This is mildly annoying for anyone who needs sessions readable from non-Ruby code.

**Comment by radar** [comment]
Would you care to submit a PR to fix this?

**Comment by charles-dyfis-net** [comment]
Happy to -- but would you suggest how best to pass that configuration around? I almost might be tempted to reuse `rails.application.config.action_dispatch.cookies_serializer` for the purpose, but given as server-side session stores aren't exactly cookies, it's not quite on-point. (On the upside, anyone using a `cookies_serializer` of `:hybrid` or `:json` is already promising that their session data can be round-tripped through JSON without harm).

**Comment by radar** [comment]
I don't know. It's up to you to figure this one out :)
