### ISSUE TITLE
Rack-cache backend config does not work

### ISSUE THREAD

**Issue by arcwhite** [redis-store/redis-rails#2]
In the readme you have this config option:

config.action_dispatch.rack_cache = {
  metastore:   'redis://localhost:6379/1/metastore',
  entitystore: 'redis://localhost:6379/1/entitystore'
}

Per https://github.com/redis-store/redis-store/issues/188, and my own experience with redis-rails 3.2.4 having the same issue on production, this does not work, and never has.

This config, on production, generates the following error message: cache error: 
Unknown storage provider: redis://[REDACTED URL THAT I KNOW WORKS]/1/metastore
/app/vendor/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/storage.rb:39:in `create_store'

**Comment by streetlogics** [comment]
+1 adding redis-rack-cache doesn't fix it, Rails 4.2.0, Ruby 2.2.0

    gem 'rails', '~>4.2.0'
    gem 'redis'
    gem 'redis-rails'
    gem 'rack-cache'
    gem 'redis-rack-cache'

**Comment by ryanbillingsley** [comment]
+1 seeing the same problem with Rails 4.2.0, Ruby 2.2.1 on Heroku.

**Comment by radar** [comment]
A patch to fix this issue would be most welcome.

**Comment by tubbo** [comment]
If anyone is still having this problem, reopen the issue. Otherwise, I'm gonna close it now because for security reasons, you should be running a higher patch version of Rails 4.2.

**Comment by milesmatthias** [comment]
Seems like this should be re-opened. I'm having this issue still. I also provided more debugging info here on why that error is happening: https://github.com/redis-store/redis-rack/issues/12
