### ISSUE TITLE
how to rescue from Redis connection failier

### ISSUE THREAD

**Issue by mzaragoza** [redis-store/redis-rails#20]
I am using redis for caching. but if for what ever reason the connection where to drop how could I change the connection to a back up cache store? 
       ```begin```
         ```  config.cache_store = :redis_store, { :host => "some_ip_address", :port => 6379, :db => 0, :namespace => Rails.env, :expires_in => 1.day } ```
       ```rescue```
```         config.cache_store = :redis_store, { :host => "localhost", :port => 6379, :db => 0, :namespace => Rails.env, :expires_in => 1.day } ```
         ```end```

**Comment by tubbo** [comment]
Take a look at the [Usage with Redis Sentinel](https://github.com/redis-store/redis-rails#usage-with-redis-sentinel) portion of the README for more information on setting up a cluster of Redis servers to store your Rails cache.
