### ISSUE TITLE
Add master/slave configuration to README (and maybe gem)

### ISSUE THREAD

**Issue by ponny** [redis-store/redis-rails#21]
I don't seem to be able to figure out how to set up my cache to use a master/slave configuration.  Is this possible?  I don't find any reference to this in the docs or the code except for the "instantiate a cluster" comment.  I tried setting my slave there but the cache attempts to write to the slave.

**Comment by rwwaskk** [comment]
same here.

**Comment by radar** [comment]
I don't have any idea how this works. Please submit a PR when you know.

**Comment by tubbo** [comment]
This is a Redis-level question and therefore out of scope for this project.
