### ISSUE TITLE
Rails 3.0 support

### ISSUE THREAD

**Issue by brandonhilkert** [redis-store/redis-rails#22]
I realize this only support 3.2, but if I fork and relax the gemspec dependencies, are there reasons it wouldn't work with Rails 3.0?

**Comment by rthbound** [comment]
@brandonhilkert have you tried?

+1 to close

**Comment by brandonhilkert** [comment]
I ended up pulling out the bits I needed and making my own.

**Comment by rthbound** [comment]
thanks!
