### ISSUE TITLE
How to pass sentinels options to Redis connection?

### ISSUE THREAD

**Issue by palexvs** [redis-store/redis-rails#23]
I'm trying to use sentinels for failover, but Rails.cache.write() does not work when Redis master is down

Sentinels are configured properly and work:
```ruby
> o = {
  url: "redis://master.local:6379/2",
  sentinels: [
    {host: "sentinel1.local", port: 26379},
    {host: "sentinel2.local", port: 26379},
  ]
}
> redis = Redis.new(o)
> redis.set('test','1')
=> OK
```

But 
```ruby
/config/application.rb

o = {
  url: "redis://master.local:6379/2",
  sentinels: [
    {host: "sentinel1.local", port: 26379},
    {host: "sentinel2.local", port: 26379},
  ]
}
config.cache_store = :redis_store, o, { expires_in: 1.day }
```

```
Rails.cache.write('test', true, {expires_in: 1.hour.to_i})
```

returns
```
Redis::CannotConnectError: Error connecting to Redis on master.local:6379 (Errno::ECONNREFUSED)
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:331:in `rescue in establish_connection'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:317:in `establish_connection'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:94:in `block in connect'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:279:in `with_reconnect'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:93:in `connect'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:350:in `ensure_connected'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:207:in `block in process'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:292:in `logging'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:206:in `process'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:112:in `call'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/newrelic-redis-2.0.2/lib/newrelic_redis/instrumentation.rb:36:in `block in call_with_newrelic_trace'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/datastores.rb:111:in `block in wrap'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/method_tracer.rb:69:in `block in trace_execution_scoped'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/method_tracer.rb:67:in `trace_execution_scoped'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/datastores.rb:108:in `wrap'
... 10 levels...
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-store-1.1.4/lib/redis/store/ttl.rb:6:in `set'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:5:in `block in set'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:29:in `_marshal'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:5:in `set'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:163:in `write_entry'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:36:in `block in write'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.10/lib/active_support/cache.rb:548:in `instrument'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:34:in `write'
  from (irb):1
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/railties-4.1.10/lib/rails/commands/console.rb:90:in `start'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/railties-4.1.10/lib/rails/commands/console.rb:9:in `start'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/railties-4.1.10/lib/rails/commands/commands_tasks.rb:69:in `console'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/railties-4.1.10/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/railties-4.1.10/lib/rails/commands.rb:17:in `<top (required)>'
  from ./bin/rails:8:in `require'
  from ./bin/rails:8:in `<main>'irb(main):002:0> 
```

**Comment by ngrennan-inflection** [comment]
I am having a like issue. I have tried setting the url to redis://foomaster , where foomaster is the cluster identifier set in sentinel. But it tries to do a dns local up on foomaster. If I set an actual redis hostname in it's place it tries to connect to it without using sentinel, and wants the password for auth.

config/redis.yml:
---
    url:
      beta: "redis://foomaster"

config/sentinels.yml:
---
    sentinels: 
      beta: [{host => "redis01.foo", port => 26379}, {host => "redis02.foo", port => 26379}, {host => "redis03.foo", port => 26379}]



config/application.rb:
---
    redis_config = YAML.load_file(Rails.root + 'config/redis.yml')['url'][Rails.env]
    sentinels_config = YAML.load_file(Rails.root + 'config/sentinels.yml')['sentinels'][Rails.env]
    redis_options = {
      "url" => redis_config,
      "sentinels" => sentinels_config,
      "role" =>  'master'
    }
    config.cache_store = :redis_store, redis_options, { namespace: 'foo' }



Errors:
---
    cache error: getaddrinfo: Name or service not known
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis/connection/ruby.rb:153:in `getaddrinfo'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis/connection/ruby.rb:153:in `connect'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis/connection/ruby.rb:212:in `connect'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:322:in `establish_connection'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:94:in `block in connect'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:279:in `with_reconnect'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:93:in `connect'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:350:in `ensure_connected'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:207:in `block in process'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:292:in `logging'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:206:in `process'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:112:in `call'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis.rb:789:in `block in get'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis.rb:37:in `synchronize'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis.rb:788:in `get'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-store-1.1.4/lib/redis/store/interface.rb:5:in `get'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:17:in `get'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-store-1.1.4/lib/redis/store/namespace.rb:13:in `block in get'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-store-1.1.4/lib/redis/store/namespace.rb:50:in `namespace'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-store-1.1.4/lib/redis/store/namespace.rb:13:in `get'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:169:in `read_entry'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/cache.rb:316:in `block in read'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/cache.rb:520:in `instrument'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/cache.rb:315:in `read'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/http/rack_cache.rb:17:in `read'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rack-cache-1.2/lib/rack/cache/metastore.rb:30:in `lookup'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:169:in `lookup'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rack-mini-profiler-0.9.2/lib/mini_profiler/profiler.rb:193:in `call'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/railties-3.2.19/lib/rails/engine.rb:484:in `call'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/railties-3.2.19/lib/rails/application.rb:231:in `call'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rack-1.4.5/lib/rack/content_length.rb:14:in `call'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/railties-3.2.19/lib/rails/rack/log_tailer.rb:17:in `call'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/rack-1.4.5/lib/rack/handler/webrick.rb:59:in `service'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
    /usr/lib64/rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'

**Comment by ngrennan-inflection** [comment]
You have to use the master identifer as the hostname in the url. Don't set a port. You also should put everything, including the expire_in within o.

 url: "redis://redismaster/2",

**Comment by dansimpson** [comment]
Should this be fully documented?  The configuration for sessions and cache differ.  Ideally the README would have working examples, as sentinel should be standard for production deployments with uptime requirements.

**Comment by radar** [comment]
Yes please do it :)

**Comment by abrisse** [comment]
+1 for the documentation

**Comment by ponny** [comment]
+1 for docs too

**Comment by radar** [comment]
My previous statement still stands: please do it.
