### ISSUE TITLE
Question about maintenance and releases

### ISSUE THREAD

**Issue by vmatekole** [redis-store/redis-rails#27]
Hi,

I noticed the latest release - v4.0.0 was in 2013 and there are no branches that supersede this release. Additionally, the latest release available on gem repos is also v4.0.0. It appears there are no current releases and yet there are recent updates to master. Could you clarify if master is actually stable to install from?
~victor

**Comment by radar** [comment]
if all_tests_pass?
  puts "is OK to install from master"
end

**Comment by radar** [comment]
Please also take the time to inspect the code for this project: https://github.com/redis-store/redis-rails/tree/master/lib. There is no code, and so there is no bugs and no need to update.
