### ISSUE TITLE
[question] Using Redis for both fragment caching and Sidekiq jobs

### ISSUE THREAD

**Issue by abitdodgy** [redis-store/redis-rails#28]
Is it possible to configure Redis so that it automatically expires cached fragments when a certain memory threshold has been reached? I'm currently using Redis to persist Sidekiq jobs. I would also like to use it as the Rails cache store, but I only want to expire certain fragments once they've occupied a memory threshold. Is it possible? From what I understand, the `expires` will kick in on the given time... but that's not desirable for me since most of my cached items would still be usable.

**Comment by tubbo** [comment]
You'd probably have to write that yourself. redis-rails is solely for using Redis as a backend for Rails' caching layer and session storage, as well as the `Rack::Cache`.
