### ISSUE TITLE
Rails 5.0 support

### ISSUE THREAD

**Issue by tokhi** [redis-store/redis-rails#30]
Try to install the gem under rails 5.

```bash
Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    rails (>= 0) ruby depends on
      railties (= 5.0.0.alpha) ruby depends on
        actionpack (= 5.0.0.alpha) ruby

    active_model_serializers (~> 0.10.0.rc2) ruby depends on
      actionpack (>= 4.0) ruby

    rails (>= 0) ruby depends on
      railties (= 5.0.0.alpha) ruby depends on
        actionpack (= 5.0.0.alpha) ruby

    rails (>= 0) ruby depends on
      railties (= 5.0.0.alpha) ruby depends on
        actionpack (= 5.0.0.alpha) ruby

    active_model_serializers (~> 0.10.0.rc2) ruby depends on
      actionpack (>= 4.0) ruby

    redis-rails (>= 0) ruby depends on
      redis-actionpack (~> 4) ruby depends on
        actionpack (~> 4) ruby
```
Any plan for rails 5 support?

**Comment by radar** [comment]
Yes, when Rails 5 comes out.

**Comment by tubbo** [comment]
@tokhi Feel free to fork this gem and edit the gemspec so that you can use it with Rails 5, but we can't officially support it until Rails 5 has been released.

**Comment by tokhi** [comment]
Ok, thanks.

**Comment by loybert** [comment]
any updates since rails5 beta has been released?

**Comment by schuylr** [comment]
+1. Rails 5 is [now in beta](http://weblog.rubyonrails.org/releases/) which is at least some assurance of architecture stability. The blog post also recommends new users begin with Rails 5. Can we re-open this?

**Comment by tubbo** [comment]
Sure thing, we should give it a shot so that when rails 5 does get released, we'll be ready for it.

**Comment by tubbo** [comment]
Hey folks. Took a second look at how RubyGems.org reports versions, and we definitely won't be able to release any version of redis-rails until Rails 5 comes out, otherwise we have to specify a beta version of the gem. Basically, the beta versions aren't reported as the "current version" of Rails on RubyGems.org, for obvious reasons (because it's not fully released yet). Therefore, I invite anyone to fork the gem and change the gemspec themselves if they wish to use redis-rails with the Rails 5.0 beta. If you do this, *please* contribute back any fixes you have to implement yourself, so that when we can finally cut over with a new version supporting the final Rails 5 version, we'll be more ready!

**Comment by rthbound** [comment]
@tubbo thanks!

Just wanting to clarify... this gem depends on a couple other redis-store gems:
```
  s.add_dependency "redis-activesupport", "~> 4"
  s.add_dependency "redis-actionpack",    "~> 4"
```

These gems in turn depend on rails. In order to release a version of redis-rails that supports rails 5, we'd need new versions of these gems (versions that depend on activesupport and actionpack from rails 5).

If one wants to jump the gun on this, they could:

1. fork this gem's dependencies
2. change those dependencies to depend on rails 5
3. change the gem name of those dependencies to something like "my-rails5-redis-activesupport"
4. release your own versions of this gem's dependencies
5. fork this gem, change it to depend on your newly released versions of this gem's dependencies
6. point to your fork of this gem in your application's Gemfile e.g.:
```
gem 'redis-rails', :git => 'https://github.com/whoeveryouare/redis-rails.git', :branch => 'whichever-branch'
```

**Comment by schuylr** [comment]
For what it's worth I [updated the page caching gem with very little trouble](https://github.com/rails/actionpack-page_caching/pull/32), aside from the tests. I'm assuming redis-rails uses most of the same ActionPack dependencies to achieve page and fragment caching.

Just bumping the gemspecs and seeing if it still works is definitely the first step.

**Comment by rthbound** [comment]
@schuylr yeah I think you're right... changing redis-activesupport and redis-actionpack dependencies to those shown below (and releasing) would allow us to have a rails 5.0 compatible redis-rails right now, no?

```
#redis-actionpack
s.add_runtime_dependency 'actionpack',  '~> 4', '< 5.1'
```
and
```
# redis-activesupport
s.add_runtime_dependency 'activesupport', '>= 3', '< 5.1'
```

Assuming someone gets those changes made and released, we should be able to update this gem's gemspec and be good to go.

**Comment by schuylr** [comment]
@rthbound Yep, `< 5.1` is perfect, assuming there's no breaking changes between the `5.0.0beta` and `5.0`. I'll give it a shot when I'm not busy and report back.

**Comment by rthbound** [comment]
@schuylr  :arrow_up: :five:

**Comment by schuylr** [comment]
Okay, so there was some prelim work already done in pull requests by @claudiob + @Empact [here](https://github.com/redis-store/redis-activesupport/pull/49) and @marcroberts [here](https://github.com/redis-store/redis-actionpack/pull/8).

[redis-rack](https://github.com/redis-store/redis-rack) also has a Rack dependency bumped to `< 3` but a release hasn't been made yet, so I forked my own to tag a release.

All said and done, I can get a correct build on a test Rails 5 environment with:

```
gem 'redis-rack', git: "git@github.com:schuylr/redis-rack.git", ref: "a01bfe5a8ee1df4af6c3a886e005896fe711aab7"
gem 'redis-activesupport', git: "git@github.com:claudiob/redis-activesupport.git", ref: "d83917b3a852a98cd0bee8709ab52e5437f7ca11"
gem 'redis-actionpack', git: "git@github.com:schuylr/redis-actionpack.git", ref: "b4b37571e3db63cf10713995e7d1ef85e3183b42"
gem 'redis-rails', git: "git@github.com:schuylr/redis-rails.git", ref: "5d1824e7f0a1d32c7b2bcbb7cf9a1c8ba9a5fd69"
```

I can also use the same gem refs above to run the tests here, which succeed on Ruby 2.3.0:

```
Schuylers-Work-Computer:redis-rails sjagr$ bundle exec rake
/Users/sjagr/.rvm/rubies/ruby-2.3.0/bin/ruby -I"lib:lib" -I test -I"/Users/sjagr/GitRepos/redis-rails/vendor/bundle/gems/rake-10.5.0/lib" "/Users/sjagr/GitRepos/redis-rails/vendor/bundle/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/redis_rails_test.rb" 
Run options: --seed 54279

# Running tests:

..

Finished tests in 0.000530s, 3773.5849 tests/s, 3773.5849 assertions/s.

2 tests, 2 assertions, 0 failures, 0 errors, 0 skips
```

We just need the pull requests on redis-activesupport and redis-actionpack to be approved (with some proper version bumps) and someone needs to make a release on redis-rack for the new underlying gems to reference.

Until then, this issue is on ice, but should be simple to finish once taken care of.

**Comment by tubbo** [comment]
@schuylr beautiful, thank you so much for doing the legwork on this.

![You Da Real MVP](http://thesource.com/wp-content/uploads/2014/05/youtherealmvp-300x166.jpg)

**Comment by schuylr** [comment]
![](https://media.giphy.com/media/3oEduMs65tbZqkMkH6/giphy.gif)

**Comment by dreyks** [comment]
So, the beta2 just came out today and I thought it would be the right time to start preliminary updates to the apps that I manage. Is there an intention to merge that pull requests? Maybe make a new `rails5` branch so that more people can easily use it and therefore provide some feedback and/or bug-reports?

**Comment by tubbo** [comment]
@dreyks I've made a couple comments on the other pull requests. When they're ready to merge, I will merge them, and release a `.pre` version of the gem so that y'all can upgrade your apps and begin testing/finding bugs. :)

**Comment by cheynewallace** [comment]
+ 1 here for moving forward with Rails 5 beta 2 support.  Just spent over an hour trying to figure out how to get this working until I read this issue.

Hats off to @schuylr  for his interim forks.  That's working for me for a temporary fix so I can continue developing my Rails 5 app.

**Comment by schuylr** [comment]
@cheynewallace It was a combined effort :) glad it's helping!

**Comment by pelcasandra** [comment]
+1

**Comment by leifg** [comment]
Can someone release a beta of this gem? Otherwise I'm unable to test my app on rails 5

**Comment by schuylr** [comment]
@leifg Did you try using the refs I listed above in your gemfile?

**Comment by tubbo** [comment]
@leifg @schuylr you can use the following git branch location in Gemfile to test your apps with the new redis-rails:

```ruby
gem 'redis-rails', github: 'redis-store/redis-rails', branch: 'master'
```

Leaving this thread open to continue the Rails 5 discussion on a high level, but we'll actually be tracking changes in the dependent projects, so please direct issue reporting and pull requests to those projects. Thanks y'all!

**Comment by troelskn** [comment]
Does anyone have any success getting redis-store to work with the latest beta3? I keep running into a brick wall.

**Comment by troelskn** [comment]
In case someone else ends up here wondering, I managed to get this running by forking the following 3 repos and editing their gemspec files:

```
gem 'redis-rack', github: "schuylr/redis-rack", branch: 'master'
gem 'redis-activesupport', github: "troelskn/redis-activesupport", branch: 'master'
gem 'redis-actionpack', github: "troelskn/redis-actionpack", branch: 'master'
gem 'redis-rails', github: "troelskn/redis-rails", branch: 'master'
```
I'll leave those forks there until a 5 version is out.

**Comment by tubbo** [comment]
Hey @troelskn, you should be able to use the 'master' branch of the canonical redis-rails, redis-actionpack, and redis-rack repositories. They should be compatible with Rails 5 from a gem perspective and I believe fixes to various updated APIs were added as well on some of the gems. If not, pull requests are always welcome.

redis-activesupport currently has an in-progress branch here that still needs to rebase against the latest master: https://github.com/redis-store/redis-activesupport/pull/49

**Comment by troelskn** [comment]
Oh, great. That does work.

I'll have a look at if I can help with activesupport/master

**Comment by zakwanhaj** [comment]
`gem 'redis-rails', github: 'redis-store/redis-rails', branch: 'master'` did not work with me. It kept saying me:
```
redis-rails was resolved to 5.0.0, which depends on
      redis-actionpack (< 5.1, >= 4) was resolved to 4.0.0, which depends on
        actionpack (~> 4)
```
and
```
redis-actionpack was resolved to 4.0.1, which depends on
      redis-rack (~> 1.5.0) was resolved to 1.5.0, which depends on
        rack (~> 1.5) 
```
when I added `gem 'redis-actionpack', github: 'redis-store/redis-actionpack', branch: 'master'`

The final format that bundle went ahead without any error is:
```ruby
gem 'redis-rack', github: 'redis-store/redis-rack', branch: 'master'
gem 'redis-actionpack', github: 'redis-store/redis-actionpack', branch: 'master'
gem 'redis-rails', github: 'redis-store/redis-rails', branch: 'master'
```

**Comment by connorshea** [comment]
Rails 5.0.0.rc1 was released today :D

https://github.com/rails/rails/releases/tag/v5.0.0.rc1

Will you be waiting until the full release, as far as I know there won't be any breaking changes between rc1 and the stable release (barring some crazy bugs).

**Comment by tubbo** [comment]
Alright folks, all the other gems have `.pre` releases now, so I've released this as `5.0.0.pre` today. We'll make a larger announcement once all the gems actually work together.

As of now, I don't have access to push to RubyGems for redis-actionpack, but I pushed prerelease gems for all other dependencies. So for now, you'll have to add the following to Gemfile to use redis-rails 5.0:

```ruby
gem 'redis-rails', '~> 5.0.0.pre'
gem 'redis-actionpack', github: 'redis-store/redis-actionpack', ref: 'v5.0.0.pre'
```

Eventually, you'll be able to just remove the entire `github:` dependency from redis-actionpack, but I need RubyGems access (or someone else needs to push) before that happens.

**Please let us know in this issue if you have any install problems.** Thanks!

**Comment by doits** [comment]
@tubbo doesn't look like rubygems got the prerelease versions already (https://rubygems.org/gems/redis-rails - there is no 5.0.0.pre)

**Comment by tubbo** [comment]
@doits give it a shot, sorry I guess I forgot to actually push this particular gem to rubygems (there's like 6 of them and they all have to move in lock-step, highly annoying...)

**Comment by tubbo** [comment]
Since i haven't heard anything back in over 20 days I'm closing this issue and assuming redis-rails is working on Rails 5 for you as well as it is for me :)

**Comment by connorshea** [comment]
@tubbo no final gem release?

**Comment by tubbo** [comment]
@connorshea I'll probably do it eventually but wanted to leave options open for last-minute bug fixes. We won't be releasing a "final" version until Rails does.

**Comment by connorshea** [comment]
@tubbo I wanted to notify you that [Rails 5 has been released today](http://weblog.rubyonrails.org/2016/6/30/Rails-5-0-final/), thanks for your work on the gem! :D

**Comment by claudiob** [comment]
@tubbo I suggest you release a new version ASAP because running `bundle update` on a project with Rails 5 and `redis-activesupport` will result in `redis-activesupport (0.0.0)` being installed.

In other words, if this is the Gemfile:

```ruby
gem 'activerecord',  '>= 5.0', '< 5.1'  # Rails framework
gem 'actionmailer',  '>= 5.0', '< 5.1'  # Rails framework
gem 'railties',      '>= 5.0', '< 5.1'  # Rails framework
[...]
gem 'redis-activesupport' # Fragment caching
```

then this is the resulting Gemfile.lock:

```ruby
GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (5.0.0)
      actionpack (= 5.0.0)
      actionview (= 5.0.0)
[...]
    rake (11.2.2)
    redis (3.3.0)
    redis-activesupport (0.0.0)
[...]
```

**Comment by tubbo** [comment]
@claudiob I'm not sure releasing a new version is going to fix that, but I plan to release major versions of all the gems today now that the final Rails 5.0.0 version has been released.

**Comment by connorshea** [comment]
redis-rack and redis-actionpack aren't usable with Rails 5 yet, unfortunately, as they use pre-release versions of the gems. I've opened PRs to try and fix this: https://github.com/redis-store/redis-actionpack/pull/11 and https://github.com/redis-store/redis-rack/pull/18

**Comment by connorshea** [comment]
So, has anyone successfully updated redis-rails with support for Rails 5?

**Comment by zakwanhaj** [comment]
@connorshea yes, I am using `gem 'redis-rails'` only. Everything is working as expected.

**Comment by claudiob** [comment]
@connorshea Me too! Working on Heroku, no problem. Thanks

**Comment by connorshea** [comment]
:/ what about without using beta releases?
