### ISSUE TITLE
Not sharing session with sidekiq web-ui

### ISSUE THREAD

**Issue by toddmetheny** [redis-store/redis-rails#34]
We recently switched to storing sessions in redis using redis-rails. Going well but for the fact that when we attempt to retry or delete from the sidekiq web ui we get a forbidden error. The sidekiq web ui is sinatra based. 

Any reason why sharing sessions with the web ui might be a challenge?

**Comment by marceloboeira** [comment]
Take a look at:
* mperham/sidekiq#1289
* mperham/sidekiq#2560

**Comment by tubbo** [comment]
@toddmetheny I'll reopen if you're still having this issue after looking at those issues, but otherwise it looks like this is solved.

**Comment by glaucocustodio** [comment]
Hi folks, I am using redis as session store too. Every time I access sidekiq web ui logged my session expires. I have seen both issues https://github.com/mperham/sidekiq/issues/1289 and https://github.com/mperham/sidekiq/issues/2560 but I still couldn't solve.

```ruby
# config/initializers/session_store.rb
options = { servers: "#{ENV['REDIS_URL']}/session" }
MyRailsApp::Application.config.session_store :redis_store, options
```

I tried many things, including putting it in the `routes.rb`:
```ruby
require "sidekiq/web"
Sidekiq::Web.use Rack::Session::Redis
mount Sidekiq::Web, at: "/sidekiq"

Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  username == "foo" && password == "bar"
end if Rails.env.production?
```

Ps: I am with `redis-rails (4.0.0)` and `sidekiq (4.1.2)`.

Thank you!

**Comment by glaucocustodio** [comment]
I found the solution. Instead `Sidekiq::Web.use Rack::Session::Redis` we should put `Sidekiq::Web.use ActionDispatch::Session::RedisStore`.

**Comment by atwoodjw** [comment]
Has anyone had luck getting this to work in Rails 5?

* rails 5.0.1
* sidekiq 4.2.9

This is my configuration. 

#### session_store.rb
```ruby
Rails.application.config.session_store :redis_store, servers: "#{ENV['REDIS_URL']}/0/session", expires_in: 36_000.seconds
```

#### routes.rb
```ruby
require 'sidekiq/web'

if ENV['SIDEKIQ_USERNAME'].present? && ENV['SIDEKIQ_PASSWORD'].present?
  Sidekiq::Web.use ActionDispatch::Session::RedisStore
  Sidekiq::Web.use Rack::Auth::Basic do |name, password|
    # This comparison uses & so that it doesn't short circuit and
    # uses `variable_size_secure_compare` so that length information
    # isn't leaked.
    ActiveSupport::SecurityUtils.variable_size_secure_compare(name, ENV['SIDEKIQ_USERNAME']) &
      ActiveSupport::SecurityUtils.variable_size_secure_compare(password, ENV['SIDEKIQ_PASSWORD'])
  end
end

mount Sidekiq::Web, at: '/sidekiq'
```

After logging into my app, I store `user_id` in the session.

```ruby
s = redis.get("session:1efd01b62ae03ca6ab051339d16455f8")
Marshal.load(s)
```=> {"_csrf_token"=>"dJ2ciDms0+vcxJlxBtvTM2oyGyUvWnzPDqEL/0gENaY=", "user_id"=>"a4d14a4d-c5db-4cb8-b99a-53dfad9a3e33"}
```

Then, I visit `/sidekiq`.

```ruby
s = redis.get("session:1efd01b62ae03ca6ab051339d16455f8")
Marshal.load(s)
=> {"session_id"=>"4289fee2b11ad53a98129a013e5d22f2766eef934ea488f8742bb4abad440895", "csrf"=>"69fbbec6e678327b56262d56d3f39af9", "tracking"=>{"HTTP_USER_AGENT"=>"cc9919c6933399f2e9fe67da47f709c5dd75ec28", "HTTP_ACCEPT_LANGUAGE"=>"66eae971492938c2dcc2fb1ddc8d7ec3196037da"}}
```

It seems that Sidekiq is overwriting the session, effectively logging users out.

Any thoughts on what's causing this?

**Comment by tubbo** [comment]
@atwoodjw What happens when you change the name of your session store namespace to something like "rails-session"?

**Comment by atwoodjw** [comment]
@tubbo Thanks for the quick reply.

I'm seeing the same behavior using `rails-session` as the namespace.

```ruby
Rails.application.config.session_store :redis_store, servers: { host: 'localhost', port: 6379, db: 0, namespace: 'rails-session' }, expires_in: 36_000.seconds
```

However, I did discover something else interesting. If I visit the Sidekiq Web-UI first, then sign into my app (writing `user_id` to the session), everything works. Sidekiq Web-UI doesn't overwrite the session on subsequent requests.

```ruby
s = redis.get("rails-session:c11ee39cea47a54df93454225acb6fd3")
Marshal.load(s)
=> {"session_id"=>"3a99287e69d3c3445ace141b019b79e4727c842e19fed88cbd71c63b22ab718e", "csrf"=>"0e12d331dc43dfce3a27ef0806bfffac", "tracking"=>{"HTTP_USER_AGENT"=>"cc9919c6933399f2e9fe67da47f709c5dd75ec28", "HTTP_ACCEPT_LANGUAGE"=>"66eae971492938c2dcc2fb1ddc8d7ec3196037da"}, "_csrf_token"=>"mRhntPvLyEifOeWsS5Yevz+ZGadivjbWHkTN+0jVk1E=", "user_id"=>"a4d14a4d-c5db-4cb8-b99a-53dfad9a3e33"}
```

**Comment by tubbo** [comment]
@atwoodjw It seems you're sharing the Rails session here:

```ruby
Sidekiq::Web.use ActionDispatch::Session::RedisStore
```

Not entirely sure what the issue is here, still...but that is probably the reason you are seeing redis-rails "take over" the session in `Sidekiq::Web`. If you're trying to accomplish some kind of authentication for the `Sidekiq::Web` route, could you implement a route constraint?

```ruby
class SidekiqRouteConstraint
  def matches?(request)
    User.find(request.session[:user_id]).admin? # just an example, but you can do anything here
  rescue
    false # the method must return true or false eventually, though
  end
end

Rails.application.routes.draw do
  mount Sidekiq::Web, \
    at: '/sidekiq',
    constraints: SidekiqRouteConstraint.new,
    anchor: false
```

**Comment by atwoodjw** [comment]
Clear case of RTFM. Sidekiq 4.2.3 added an option to disable it's session. mperham/sidekiq#3183

Thanks for the help troubleshooting.

```ruby
require 'sidekiq/web'

Sidekiq::Web.set :sessions, false
mount Sidekiq::Web, at: '/sidekiq'
```

**Comment by tubbo** [comment]
No problem, glad it's working for ya!

**Comment by soundasleep** [comment]
I found (on Rails 5) that I had to move the sessions set to an initializer, outside of the `routes.rb`:

```
require 'sidekiq/web'
Sidekiq::Web.set :sessions, false
```

And now it works! Thank you for the fix!!

**Comment by valterbarros** [comment]
Thank you @atwoodjw

**Comment by wimpog** [comment]
> I found (on Rails 5) that I had to move the sessions set to an initializer, outside of the `routes.rb`:
> 
> ```ruby
> require 'sidekiq/web'
> Sidekiq::Web.set :sessions, false
> ```
> 
> And now it works! Thank you for the fix!!

Which initializer should this be in? Could you please specify the full path/file? Thank you!

**Comment by webzorg** [comment]
> Clear case of RTFM. Sidekiq 4.2.3 added an option to disable it's session. [mperham/sidekiq#3183](https://github.com/mperham/sidekiq/pull/3183)
> 
> Thanks for the help troubleshooting.
> 
> ```ruby
> require 'sidekiq/web'
> 
> Sidekiq::Web.set :sessions, false
> mount Sidekiq::Web, at: '/sidekiq'
> ```

I think its good practice to only leave mount line in routes, and move rest to the initializer.
