### ISSUE TITLE
Usage with connection_pool gem?

### ISSUE THREAD

**Issue by jeffblake** [redis-store/redis-rails#37]
Hi,

I can't seem to figure out how to use a pool with the `:redis_store`.

Is this supported?

I've tried the following but none of the `pool` options seem to be read during initialization.

```
uri = URI.parse(ENV.fetch('REDIS_PROVIDER'))

Rails.application.config.session_store :redis_store, {
  servers: {
    host: uri.host,
    port: uri.port || nil,
    password: uri.password,
    namespace: 'sessions',
    pool: 'test'
  },
  domain: :all,
  tld_length: 2,
  namespace: :session,
  pool_size: 'test',
  pool: 'test'
}
```

**Comment by jeffblake** [comment]
Ah, finally figured out why the options wouldn't recognized.

https://github.com/redis-store/redis-rack/blob/master/lib/rack/session/redis.rb

That's the code I was looking at. It looks like the connection pool commit has not been released into a new gem version yet... so

gem 'redis-rack', github: 'redis-store/redis-rack', branch: 'master'

did the trick.

**Comment by tubbo** [comment]
@jeffblake Whoops, that one definitely slipped through the cracks. That said, [redis-rack](https://github.com/redis-store/redis-rack) has its own issue tracker so I'll be closing this issue and releasing a new version of redis-rack later today.
