### ISSUE TITLE
Rake 11 support

### ISSUE THREAD

**Issue by connorshea** [redis-store/redis-rails#38]
Would you be able to loosen the rake requirement in the gemspec to allow Rake 11?

Changelog here: https://github.com/ruby/rake/blob/master/History.rdoc

**Comment by tubbo** [comment]
Is there any benefit to bumping the version? We only use Rake for development tasks, like building the gem and maybe running tests. Rake is also a development dependency for redis-rails, so it doesn't have any effect on apps that are using this gem.

**Comment by connorshea** [comment]
This is what I get for lacking reading comprehension, thought it was a normal requirement, sorry about that!
