### ISSUE TITLE
have trouble install redis-rails gem 

### ISSUE THREAD

**Issue by jennytech** [redis-store/redis-rails#39]
![6](https://cloud.githubusercontent.com/assets/16144214/15762937/69325c2c-28d5-11e6-9a88-0a700d25db2f.png)

**Comment by tubbo** [comment]
What happens after you follow the instructions in the error message? This is not related to redis-rails. Please install a not shitty version of Ruby. :-)

**Comment by w-zengtao** [comment]
gem 'redis-rails', git: 'https://github.com/redis-store/redis-rails.git' @jennytech

**Comment by w-zengtao** [comment]
some errors in Gemfile @tubbo

**Comment by tubbo** [comment]
@w-zengtao and @jennytech, can you folks try to install redis-rails under the latest Ruby version? it seems your version is outdated and might be causing issues on Windows.

**Comment by moazzamk** [comment]
I had the same issue on Rails 5, Ruby 2.3 on OSX. Thanks @w-zengtao for the solution.

**Comment by tubbo** [comment]
closing, and working with the team to add the minimum requirements on issue posting so that non-issues like this and/or duplicates aren't reported.

**Comment by jennytech** [comment]
how to do it?

**Comment by jennytech** [comment]
@moazzamk did u make ut?

**Comment by tubbo** [comment]
@jennytech @moazzamk @w-zengtao this should be solved by specifying the version:

```ruby
gem 'redis-rails', '~> 5'
```

You shouldn't need the github dependency anymore.
