### ISSUE TITLE
Push stable version for Rails 5

### ISSUE THREAD

**Issue by jeroenvisser101** [redis-store/redis-rails#41]
Now that Rails 5 has landed, is there anything that needs to be done before we can push a 5.0.0 to rubygems?

**Comment by tubbo** [comment]
@jeroenvisser101 Doesn't seem so! I haven't heard of any issues in the beta/RC period, so I'm planning to release major version gems for all the redis-store projects at some point today.

**Comment by alexhanh** [comment]
+1

**Comment by jeroenvisser101** [comment]
Thanks @tubbo, I'll close this since stable versions have been released.

PS. @alexhanh +1 comment push notifications to all participants, please use the "reactions" GitHub introduced, thanks! :)
