### ISSUE TITLE
redis-actionpack depends on prereleases

### ISSUE THREAD

**Issue by connorshea** [redis-store/redis-rails#45]
redis-rails depends on redis-actionpack which in turn depends on some prerelease versions of gems. redis-actionpack needs to be updated so it doesn't depend on prereleases. Unfortunately my issue in the redis-actionpack repo hasn't seen a response yet.

See https://github.com/redis-store/redis-actionpack/issues/10

**Comment by tubbo** [comment]
sorry for the delay on this @connorshea but i'm gonna track discussion in the other issue.
