### ISSUE TITLE
On rubygems homepage, pease add link to source code

### ISSUE THREAD

**Issue by jaredbeck** [redis-store/redis-rails#47]
Current links:

- Homepage
- Documentation

Recommended links:

- Homepage
- Source Code
- Documentation
- Wiki
- Mailing List
- Bug Tracker

Most of these links can only be added by a gem owner, they're not in the gemspec.

Thanks!

**Comment by tubbo** [comment]
@jaredbeck We don't have a mailing list for this project, but all other links have been added. Thanks for letting us know about this!

**Comment by jaredbeck** [comment]
> .. all other links have been added ..

Yay, thanks!
