### ISSUE TITLE
Please add a changelog

### ISSUE THREAD

**Issue by jaredbeck** [redis-store/redis-rails#48]
I am currently running redis-rails 4 and I want to upgrade to 5, but there doesn't seem to be an easy way to figure out what changed. I looked at "releases" on GH, and I looked for a file named CHANGELOG.md, HISTORY.md, or NEWS.md, but I couldn't find any of them.

You're probably aware of http://semver.org/, but you may also find http://keepachangelog.com interesting.

Let me know if I can help. I've contributed changelogs to many projects.

**Comment by tubbo** [comment]
Definitely a good call for any project. I would rather publish the changeling in GitHub release descriptions than create a whole separate file, just because it's easier to browse and have all your information in the same place. That doesn't really help for past versions, but for future versions I find the interface much easier to use. If you'd like to contribute a `CHANGELOG` that focuses on past releases which GitHub can't really deal with (this gem has been around for a while and has went through several refactors, leading to the multiple-gem thing you see today). We have the time to contribute release notes for future releases, but I'm not sure any of us have enough time to go back and pore through all the changes between versions to create a useful `CHANGELOG` right now. 

Thoughts on this folks? @jodosha @krainboltgreene @marceloboeira @radar @shiro16 @schuylr ?

**Comment by jaredbeck** [comment]
> Definitely a good call for any project. I would rather publish the changeling in GitHub release descriptions than create a whole separate file, just because it's easier to browse and have all your information in the same place. 

I prefer a single file so I can search it using normal tools like `ctrl-f`, or `grep`. But, GH releases are better than nothing. Thank you for taking action on this. It's hard to justify upgrading to 5 if I have no idea what may break. Thanks!

**Comment by schuylr** [comment]
I think a `CHANGELOG` is nice when you've pulled down the gem and don't want to crack open Github just to see some quick notes, but falls short when you're trying to go into much more depth.

I like the Github releases when dealing with more elaborate software suites that require heavier notes and documentation about known bugs, upgrades, features, and fixes, for example [rancher/rancher](https://github.com/rancher/rancher/releases).

@jaredbeck To answer your concerns on the Rails 5 upgrade, it has been pretty heavily discussed in #30 - and to recap it's mostly just been some version bumps on the gem dependencies to keep bundler happy, not much else seems to be affected much.

A Rails 5 note in the `README.md` might be a good stopgap in the meantime to address the immediate concerns.

**Comment by jaredbeck** [comment]
> [version 5 of redis-rails] has been pretty heavily discussed in #30 .. it's mostly just been some version bumps on the gem dependencies to keep bundler happy, not much else seems to be affected much.

Thanks Schuyler, that should give ups the confidence to update.

**Comment by tubbo** [comment]
@jaredbeck Sorry this kinda fell by the wayside. When trying to think of a changelog today, I wondered whether it would be better to have a combined changelog for all changes in all dependent gems. After all, redis-rails is just pulling in other gems like redis-actionpack and redis-activesupport that do the real work. I'll also keep release notes for each gem separately in the GitHub Releases.

If a combined changelog is what we need, then I propose we put it on the redis-store.github.io page so it's easy to access and centralized.

**Comment by jaredbeck** [comment]
> .. I wondered whether it would be better to have a combined changelog for all changes in all dependent gems.

When I review PRs on my own projects, I ask PR authors to update the changelog. This way, I don't have to write the changelog when it comes time to do a release. Given that all of your projects are in different repos (as they should be), I think that maintaining a single changelog, in only one repo, would introduce a pain point for you in your PR review process. So, I'd recommend separate changelogs for each gem, stored in each gem's repo. This is also more conventional, and thus more likely to be found by, and help your users.

**Comment by tubbo** [comment]
Sounds good. I think it's best to start with the actual [redis-store](https://github.com/redis-store/redis-store) gem since that one has the most usage (all the rest of the gems depend on it in some way).

On 11/09, Jared Beck wrote:
> > .. I wondered whether it would be better to have a combined changelog for all changes in all dependent gems.
> 
> When I review PRs on my own projects, I ask PR authors to update the changelog. This way, I don't have to write the changelog when it comes time to do a release. Given that all of your projects are in different repos (as they should be), I think that maintaining a single changelog, in only one repo, would introduce a pain point for you in your PR review process. So, I'd recommend separate changelogs for each gem, stored in each gem's repo. This is also more conventional, and thus more likely to be found by, and help your users.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/redis-store/redis-rails/issues/48#issuecomment-259462037

-- 
- T

**Comment by tubbo** [comment]
@jaredbeck Unless there's anything else that needs to be done I think we can close this.

**Comment by jaredbeck** [comment]
> @jaredbeck Unless there's anything else that needs to be done I think we can close this.

Sounds good, unless there are other gems in the organization that need changelogs. Thanks.

**Comment by tubbo** [comment]
A lot of them are pretty low-maintenence, so I was thinking I'd add
changelogs on anything that doesn't have one as I encounter each
project. For example, `redis-sinatra` isn't used nearly as much as
`redis-rails`.

On 11/14, Jared Beck wrote:
> > @jaredbeck Unless there's anything else that needs to be done I think we can close this.
> 
> Sounds good, unless there are other gems in the organization that need changelogs. Thanks.
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/redis-store/redis-rails/issues/48#issuecomment-260426960

-- 
- T
