### ISSUE TITLE
Cache not deleted.

### ISSUE THREAD

**Issue by duhanov** [redis-store/redis-rails#5]
I have view:
<%cache "global-#{@site.id}-#{is_admin}-#{is_themer}-#{params.inspect}" do%>
<%=DateTime.now%>

<%end%>

I have Sweeper:
class ProductSweeper < ActionController::Caching::Sweeper
  observe Product  
  def after_destroy(el)
    expire_cache(el)
  end
  def after_save(el)
    expire_cache(el)
  end
  def expire_cache(el)
      expire_fragment("*global_#{el.site_id}_*")
      expire_fragment("global_#{el.site_id}_*")
  end
end

In console (redis-cli monitor) i view:
1392717902.183876 "del" "views/*global-43-*"
1392717903.443281 "get" "views/global-43-true-true-{\"id\"=>\"\", \"controller\"=>\"catalog\", \"action\"=>\"index\"}"

But cache dont refresh!!

(Rails3, Ruby 1.9, Nginx, Passenger)

**Comment by tubbo** [comment]
Hey @duhanov, are you still having this issue?
