### ISSUE TITLE
Could not find cache store adapter for redis_store (rails 5.0.0.1 and heroku)

### ISSUE THREAD

**Issue by gbrl** [redis-store/redis-rails#50]
Greetings!

I've tried for a half hour and I just can't get this gem to work with rails 5 and heroku. I've tried multiple solutions outlined here:

https://stackoverflow.com/questions/9774541/could-not-find-cache-store-adapter-for-redis-store

None of them work.  Any advice? I'm using the RedisCloud add-on.

Gemfile:

```
gem 'redis-rails'
```

production.rb

```
  # Use a different cache store in production.
  config.cache_store = :redis_store, ENV['REDISCLOUD_URL']
```

Do I need the other gems as well? redis, redis-store? Do I need to lock onto a specific version? 
Thanks for your time!!

**Comment by tubbo** [comment]
Use `gem 'redis-rails', '~> 5'` in your Gemfile.

**Comment by gbrl** [comment]
Thanks!!

**Comment by kowal** [comment]
Had same issue with rails 4, however, setting up version in Gemfile didn't help:

```ruby
# Gemfile
gem 'redis-rails', '~> 4'

# config/environments/production.rb
config.cache_store = :redis_store, ENV['REDIS_URL'], { expires_in: 24.hours }
```

This setup resulted in:
```ruby
Could not find cache store adapter for redis_store (cannot load such file -- active_support/cache/redis_store)
```

Solution (workaround) was to move cache_store setup from env file to Rails initializer:
```ruby
# config/initializers/redis_store.rb
Rails.application.config.cache_store = :redis_store, ...
```

**Comment by tubbo** [comment]
@kowal That doesn't seem right. Moving the configuration from the environment file to the initializer just changes when the code is executed, it doesn't change the environment nor the files that are loaded into it, which is the error you were receiving. Are you using Spring by any chance?

**Comment by kowal** [comment]
You're right @tubbo, setting `cache_store` in initializer did not actually set proper store backend. It wasn't working for me for silly reason - gemfile entry was in `development` group :/

**Comment by tubbo** [comment]
Ahh yeah that's a rough one. Glad you got it figured out though!
