### ISSUE TITLE
No sentinels available

### ISSUE THREAD

**Issue by phspies** [redis-store/redis-rails#53]
Got the following configuration:

`        SENTINELS = [
        {:host => "server1", :port => 6379},
        {:host => "server2", :port => 6379},
        {:host => "server3", :port => 6379},
        {:host => "server4", :port => 6379}
        ]

        sentinel_config = {
          url: "redis://redis1/2",
          role: "master",
          sentinels: SENTINELS
        }
        config.cache_store = :redis_store, sentinel_config.merge(
                namespace: "cache",
                expires_in: 1.days
        )
        config.session_store :redis_store, {
                servers: sentinel_config.merge(
                namespace: "sessions"
                ),
                expires_in: 2.days
        }`

Rails log says the following:

I, [2016-11-14T17:42:22.177577 #9661]  INFO -- : method=GET path=/ format=html controller=Devise::SessionsController action=new status=500 error='ActionView::Template::Error: No sentinels available.' duration=37.39 view=0.00 db=2.48 ip=xxx.xxx.xxx
F, [2016-11-14T17:42:22.181366 #9661] FATAL -- :
ActionView::Template::Error (No sentinels available.):

**Comment by tubbo** [comment]
That seems to be getting thrown by https://github.com/redis/redis-rb/blob/d75708f6e05d9bba7dfec65880f9a55252f3fd2a/lib/redis/client.rb#L567, which is the underlying client that talks to Redis used by this gem and many other libraries. Can you confirm that your Redis Sentinel server IPs are not only up and running, but also connectable from your app server's machine?

**Comment by phspies** [comment]
This is from the rails server...

`redis-cli -h .....68
.....68:6379> info
# Server
redis_version:3.0.7
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:6a943c0b5bf37fa1
redis_mode:sentinel
os:Linux 4.4.0-47-generic x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:5.3.1
process_id:55852
run_id:495c96e33be71dd84bf64d235c513e779cf31e4b
tcp_port:6379
uptime_in_seconds:65762
uptime_in_days:0
hz:18
lru_clock:2753833
config_file:/etc/redis/sentinel.conf

# Sentinel
sentinel_masters:1
sentinel_tilt:0
sentinel_running_scripts:0
sentinel_scripts_queue_length:0
master0:name=redis-cluster,status=ok,address=<ip>:6379,slaves=1,sentinels=5`

**Comment by phspies** [comment]
@tubbo, any idea why I'm getting this error?

**Comment by tubbo** [comment]
@phspies still looking into it, unfortunately I don't have a lot of experience with Redis Sentinel as none of my projects so far have used it...

**Comment by tubbo** [comment]
@phspies Hey I think this is due to a documentation fail, which I just resolved.

The `servers:` setting here should be set to an Array, not a Hash:

```ruby
    sentinel_config = {
      url: "redis://redis1/2",
      role: "master",
      sentinels: SENTINELS
    }

    config.cache_store = :redis_store, sentinel_config.merge(
            namespace: "cache"
    ),
    expires_in: 1.day

    config.session_store :redis_store, {
            servers: [
              sentinel_config.merge(
                namespace: "sessions"
              )
            ],
            expires_in: 2.days
    }
```
