### ISSUE TITLE
config.session_store usage description has an error

### ISSUE THREAD

**Issue by toshi1973814** [redis-store/redis-rails#61]
I am using Rails 3.2.18.

I followed your usage description below

> MyApplication::Application.config.session_store :redis_store, servers: { host: "localhost",
                                                                         port: 6379,
                                                                         db: 0,
                                                                         password: "mysecret",
                                                                         namespace: "session"
                                                                       },
                                                                       expires_in: 90.minutes

but session expirations were not set on browsers.
Then I googled and found that "expires_in" should be replaced by "expire_after".
You should fix the description above.

**Comment by tubbo** [comment]
@toshi1973814 Thanks for the tip, `servers:` is supposed to be an Array so yes the README is wrong. I've changed it so people won't be confused in the future.
