### ISSUE TITLE
Let expire method accept array

### ISSUE THREAD

**Issue by vlado86** [redis-store/redis-rails#62]
Currently when I use Rails.cache.fetch with array, it translates it to cache_key, for example:
`Rails.cache.fetch ['model', model.id, 'feature']`

This creates key such as "model/1/feature".

But when I want to expire given key, I can only pass string to expire method, so to expire key from example I have to use:
`Rails.cache.expire ['model', model.id, 'feature'].join('/')`

Also if I were to use model instance as a key, to expire it I would have to use model instance cache_key and pass it to expire method.

Is it possible to allow expire method accept same arguments that are accepted by fetch method?

**Comment by tubbo** [comment]
@vlado86 What version of Rails are you using?

**Comment by vlado86** [comment]
We're still at Rails 4.2.7.1. I'm happy to hear this feature will be present for us in new rails :)
