### ISSUE TITLE
documentation mistakenly suggests pinning 4.0 version for rails 3.1 usage

### ISSUE THREAD

**Issue by michael-groble** [redis-store/redis-rails#63]
The README states  to pin the gem as follows in order to use this in rails 3.1+
```
gem 'redis-rails', '~> 4'
```
but that leads to `redis-actionpack` trying to pull in `actionpack` ~>4 which is not satisfied in Rails 3.x.

We were hoping it would be as easy as this to get the pool support in Rails 3, but seems like the documentation might not be quite right about that.

**Comment by tubbo** [comment]
@michael-groble Try using the 3.x version, but I'm not sure the connection pool changes are backported.

**Comment by tubbo** [comment]
@michael-groble did this work for you?

**Comment by michael-groble** [comment]
I tried [this](https://github.com/redis-store/redis-activesupport/compare/master...deliveroo:hack-dependencies-and-versions-for-rails-3) actually and still have problems.  Within 15 minutes or so of deployment, puma is not using the cache and going straight to the database for all requests.  I have not dug into it further yet.

**Comment by tubbo** [comment]
That is quite interesting. I know the cache interface has changed quite a bit since then. I'll see what I can do about backporting the connection pool fix and reproducing what you got.

**Comment by tubbo** [comment]
@michael-groble I'm looking at this issue but I was wondering what versions of redis-rails, redis-activesupport, and redis-actionpack you're using...had trouble getting this gem set up in Appraisals for Rails 3.

**Comment by michael-groble** [comment]
it is quite a bit messy and possibly an issue with our unique combination of gems.  we are using railslts and our own forks for some.

relevant bits from our gemfile:
```
gem 'rails', '~> 3.2.22'
gem 'redis', git: 'https://github.com/deliveroo/redis-rb.git', branch: 'distributed_mget'
gem 'redis-rails', '~> 3.2'
gem 'redis-activesupport', git: 'https://github.com/deliveroo/redis-activesupport.git', branch: 'hack-dependencies-and-versions-for-rails-3'
gem 'rack-cache', git: 'https://github.com/mezis/rack-cache.git', branch: 'fixes'
gem 'redis-rack-cache', git: 'https://github.com/deliveroo/redis-rack-cache', branch: 'sharding'
```
which gives us:
```
redis-actionpack (3.2.4)
redis-activesupport (3.2.4)
redis-rack (1.4.4)
redis-rack-cache (1.2.4)
redis-rails (3.2.4)
redis-store (1.1.7)
```

**Comment by tubbo** [comment]
@michael-groble what happens when you don't specify a version for redis-rails?

**Comment by michael-groble** [comment]
it still grabs the same 3.2.4 version, only diff in lock file the specifier:

```
-  redis-rails (~> 3.2)
+  redis-rails
```

**Comment by tubbo** [comment]
@michael-groble that makes sense, because it's trying to grab the version that works for redis-actionpack and redis-activesupport. Today, I set up this gem for use with [thoughtbot/appraisal](https://github.com/thoughtbot/appraisal), so that in the future the versioning of the redis-store gems will only communicate the level of changes in the gem itself, and *not* with dependencies such as actionpack and activesupport. the gem is currently tested against Rails 4 and Rails 5, and i'm working on rails 3 support as well but I think it'll require a bump from redis-actionpack.
