### ISSUE TITLE
Sentinel redis_mode value

### ISSUE THREAD

**Issue by AmirMingaliev** [redis-store/redis-rails#65]
Hi guys. I'm sorry in advance if this question is a little bit stupid :) 

We use redis as cache store connected to redis sentinel. We have tested our application and it seems that everything is okay. But we noticed that `Rails.cache.stats` receives that `redis_mode=standalone`. So the question is shouldn't it receive `redis_mode=sentinel` or it's fine?

Thanks in advance, guys!

**Comment by tubbo** [comment]
@AmirMingaliev `Redis::Store#stats` is going to tell you information from the *server*, not the client. That means the redis_mode on the server you've connected to is "standalone", so I think that's a Redis server config issue.

**Comment by AmirMingaliev** [comment]
I have tried to connect through `redis-cli` to redis sentinel 26379 port and it receives me `redis_mode=sentinel`. It looks like `Rails.cache.stats` shows stats from redis sentinel's master.

**Comment by tubbo** [comment]
@AmirMingaliev that would make sense to me, redis/redis-rb might be a better place to open this discussion so that anyone who makes software based off the Redis client can benefit from it
