### ISSUE TITLE
Master-slave Rails cache

### ISSUE THREAD

**Issue by aijanai** [redis-store/redis-rails#68]
Hello,

this seems not to be anywhere: is it possible to use a master-slave setup to perform Rails cache reads from a slave and writes to the master?

I'm just inquiring if this feature is currently supported or plans to be supported in the near future.

Thanks

**Comment by tubbo** [comment]
@aijanai I think you can do that with [Redis Sentinel](https://redis.io/topics/sentinel), and we do support Sentinel connections by allowing you to specify multiple hosts in most configuration spots.

**Comment by aijanai** [comment]
Thanks for your reply, first.

I am trying to shed some light since there is some confusion: isn't Sentinel just an automated failover mechanism that CAN provide to a client a list of masters and slaves so that I can open 2 distinct connections (one to slaves and one to master)?
Does it provide out of the box traffic split?

Thanks

**Comment by tubbo** [comment]
@aijanai not sure if it provides out-of-box traffic splitting, but I think with either https://github.com/redis-store/redis-store/blob/master/lib/redis/distributed_store.rb or two separate clients, you can get that to work.

redis-store is a subclass of redis.rb, so you can follow the README here to learn how to connect with Sentinel: https://github.com/redis/redis-rb#sentinel-support
