### ISSUE TITLE
no _dump_data is defined for class Proc

### ISSUE THREAD

**Issue by seyhunak** [redis-store/redis-rails#7]
I'm getting following error, if i try to dump tweets (about 1000) to the redis using redis-rails. What is the workaround?

> no _dump_data is defined for class Proc
redis-store (1.1.4) lib/redis/store/marshalling.rb, line 29

**Comment by tubbo** [comment]
I think this was resolved in a patch release, give the update a shot and reopen if it doesn't fix your problem.

**Comment by dobryakov** [comment]
@tubbo, I have same error now (gem version 4.0.0). What patch release do you mean? Could you please give me a direct reference to this fix?

**Comment by tubbo** [comment]
@dobryakov try doing a `bundle update redis-rails`

**Comment by dobryakov** [comment]
@tubbo sorry, it does not help:

bundle show | grep redis
  * redis (3.3.1)
  * redis-actionpack (5.0.0)
  * redis-activesupport (5.0.1)
  * redis-rack (2.0.0.pre)
  * redis-rails (5.0.1)
  * redis-store (1.2.0)

TypeError: no _dump_data is defined for class Proc
File "/usr/local/rvm/gems/ruby-2.3.1/gems/redis-store-1.2.0/lib/redis/store/marshalling.rb" line 29 in dump
File "/usr/local/rvm/gems/ruby-2.3.1/gems/redis-store-1.2.0/lib/redis/store/marshalling.rb" line 29 in _marshal
File "/usr/local/rvm/gems/ruby-2.3.1/gems/redis-store-1.2.0/lib/redis/store/marshalling.rb" line 5 in set
...

Have you any ideas?
