### ISSUE TITLE
How to integrate with Redis cluster?

### ISSUE THREAD

**Issue by fguillen** [redis-store/redis-rails#72]
We have not implemented Sentinel, but we have a Redis cluster.

How can we use "redis-rails" with our cluster?

We have tried:

    CampaignPlatform::Application.config.cache_store = :redis_store, ["redis://server1:6379/0/", "redis://server2:6379/0/"]

And it works.. some times:

```
irb(main):007:0> Rails.cache.read("key")
=> nil
irb(main):008:0> Rails.cache.read("key2")
Redis::CommandError: MOVED 4998 172.29.40.12:6379
```

**Comment by tubbo** [comment]
@fguillen In redis/redis-rb#546, there was some discussion over adding redis-cluster support directly to the `Redis` client (of which `Redis::Store` inherits from), but that fizzled out. At this time, there's no cluster support in redis-store, so `MOVED` responses (which are supposed to be handled by the client) are interpreted as an error by the Redis client. We should really add some kind of support to redis-store if redis isn't going to add it themselves, but for now you can alternatively use https://github.com/film42/redis-cluster-activesupport with the corvus proxy to make it work.

more info on the error: https://serverfault.com/questions/812156/redis-cluster-error-moved

Sorry I can't offer much more help!

**Comment by fguillen** [comment]
@tubbo thanks a lot for pointing me in the right direction 👍

**Comment by supercaracal** [comment]
```ruby
CampaignPlatform::Application.config.cache_store = :redis_store, { cluster: %w[redis://server1:6379/0/ redis://server2:6379/0/] }
```
