### ISSUE TITLE
Running common redis server and sharing cache for different instances

### ISSUE THREAD

**Issue by nitvik** [redis-store/redis-rails#74]
I got two instances (i.e. Rails servers). Instance 1 and Instance 2.
They run on same code because they are the backend of a load balancer.

Now I want them to have a common redis server instead of having their own redis-servers.

So I got this configured for redis-store gem which can do redis caching for rails:

**application.rb**

    config.cache_store = :redis_store, "redis:/#{ENV['REDIS_SERVER']}/:6379/0/cache", { expires_in: 10.minutes }

The problem is, that even though they are running on same redis server but still they are using **different namespace or database** due to which I am getting different information sometimes due to different caches.

I checked `redis-cli` and did `KEYS *`
Output:

    1) "queues"
     2) "INSTANCE2:7773:815a2"
     3) "processes"
     4) "INSTANCE1:7316:aavmk"
    5) "stat:processed"

As you can see INSTANCE1 and INSTANCE2 are getting prefixed , I want that both should share the data on redis but this is not gonna happen if server name is going to be prefixed.

Rails version 4.1.4

**Comment by tubbo** [comment]
> The problem is, that even though they are running on same redis server but still they are using different namespace or database

Why are you isolating each app server's Redis cache? For most setups I've seen, we typically store every instance's cache in the same place.

**Comment by nitvik** [comment]
Because I need to delete cache on some update or create callback, but when I do that then it gets deleted/refreshed only on 1 instance and other instance keeps showing old data.

**Comment by tubbo** [comment]
@nitvik I see, but why the different DB for each server? Couldn't you just use the same DB/namespace for all servers?

**Comment by nitvik** [comment]
> @nitvik I see, but why the different DB for each server? Couldn't you just use the same DB/namespace for all servers?

This config:
`config.cache_store = :redis_store, "redis:/#{ENV['REDIS_SERVER']}/:6379/0/cache", { expires_in: 10.minutes }`

is same for all instances, so I am using same DB and same Namespace, but still it is prefixing it with server name automatically, correct me if I am wrongly configuring or pardon my mistake, but according to me I have configured it correctly and name space and db are same too as you can see in the config.

The` ENV['REDIS_SERVER']`  is also same.

**Comment by tubbo** [comment]
@nitvik What is `$REDIS_SERVER` set to? It should be the same for both instances, and *not* 127.0.0.1

**Comment by nitvik** [comment]
$REDIS_SERVER is `10.0.0.3`, not 127.0.0.1, like I said, I am able to use the same redis instance for both rails servers but I am not able to use the same namespace.

Here is output from INSTANCE 1:
`[:redis_store, "redis:/10.0.0.3/:6379/0/cache", {:expires_in=>600 seconds}]`
And this output from INSTANCE 2:
`[:redis_store, "redis:/10.0.0.3/:6379/0/cache", {:expires_in=>600 seconds}]`

**Comment by tubbo** [comment]
@nitvik I'm not able to reproduce this on a clustered application:

![fetch-foo](https://user-images.githubusercontent.com/113026/31408829-d1dd7fd0-add7-11e7-9035-9b81139b2a73.png)

Can you make sure `/etc/hosts` or possibly firewall configuration isn't getting in the way? I'd almost bet that it's something outside of your configuration here, because everything you've posted looks totally fine to me.

**Comment by nitvik** [comment]
Hmm, thanks for trying to reproduce, looks like issue at my end then, I got really weird bug.

I did this on INSTANCE 1:
```
irb(main):002:0> Rails.cache.fetch("foo") { "bar" }
=> "bar"
irb(main):003:0> Rails.cache.fetch("foo")
=> "bar"
```

And after that I went to other instance and did this:
```
irb(main):001:0> Rails.cache.fetch("foo")
=> nil
```

Got nil instead of bar, and then I set it to bar2 on instance 2

```
irb(main):002:0> Rails.cache.fetch("foo") { "bar2" }
=> "bar2"
irb(main):003:0> Rails.cache.fetch("foo")
=> "bar2"
```

And then I went back to Instance 1:
```
irb(main):004:0> Rails.cache.fetch("foo")
=> "bar"
```

Its still bar, even though I updated to bar2 in other. They both are using same redis instance but namespace is prefixed with server name.

I will have to check whats getting in the way , a firewall or something else, I don't know, 

will update this thread with the solution if I find one. Thanks.

**Comment by tubbo** [comment]
@nitvik you might also want to restart all of your app servers (with `touch tmp/restart.txt` or whatever) just to ensure that **config/environments/production.rb** is being re-loaded.

**Comment by nitvik** [comment]
> @nitvik you might also want to restart all of your app servers (with touch tmp/restart.txt or whatever) just to ensure that config/environments/production.rb is being re-loaded.

I had done that. Not a problem with it.

I changed the URL to a Hash of config and it worked.

```
config.cache_store = :redis_store, {
      host: "#{ENV['REDIS_SERVER']}",
      port: 6379,
      db: 0,
      namespace: "cache",
      expires_in: 10.minutes
}
```

The above worked. With URL string it wasn't working.

**Comment by nitvik** [comment]
Nope, that didn't do anything good too.

I finally fixed the issue by replacing URL string with Hash Config.

```
config.cache_store = :redis_store, {
      host: "#{ENV['REDIS_SERVER']}",
      port: 6379,
      db: 0,
      namespace: "cache",
      expires_in: 10.minutes
}
```

Now it works perfectly alright. This proves that issue was in the URL string.

**Comment by tubbo** [comment]
I'm also using a URL string in my configuration. Perhaps it had to do with the combination of a URL and options?

**Comment by nitvik** [comment]
I did redis-cli and found out that URL and Hash Config are doing different name space.

When I configured this:
`config.cache_store = :redis_store, "redis:/#{ENV['REDIS_SERVER']}/:6379/0/cache", { expires_in: 10.minutes }`
Then I got this Namespace in redis-cli
`":6379:product/index"`
The name space is coming out to be the port of redis.

And when I configured this:
```
config.cache_store = :redis_store, {
      host: "#{ENV['REDIS_SERVER']}",
      port: 6379,
      db: 0,
      namespace: "cache",
      expires_in: 10.minutes,
      raise_errors: false
    }
```
Then I got the right namespace, which is cache.
`"cache:product/index"`


Seems to be bug with the URL parsing. You should be able to reproduce it.


My Gemfile.lock so that you know the versions.
```
redis (3.3.3)
    redis-actionpack (5.0.1)
      actionpack (>= 4.0, < 6)
      redis-rack (>= 1, < 3)
      redis-store (>= 1.1.0, < 1.4.0)
    redis-activesupport (5.0.3)
      activesupport (>= 3, < 6)
      redis-store (~> 1.3.0)
    redis-namespace (1.5.3)
      redis (~> 3.0, >= 3.0.4)
    redis-rack (2.0.2)
      rack (>= 1.5, < 3)
      redis-store (>= 1.2, < 1.4)
    redis-rack-cache (2.0.1)
      rack-cache (~> 1.6.0)
      redis-store (~> 1.3.0)
    redis-rails (5.0.2)
      redis-actionpack (>= 5.0, < 6)
      redis-activesupport (>= 5.0, < 6)
      redis-store (>= 1.2, < 2)
    redis-store (1.3.0)
      redis (>= 2.2)
```

**Comment by tubbo** [comment]
Ah, interesting...I think that might be because your URL is malformed. Here's an example using "localhost" as the REDIS_SERVER:

```ruby
uri = URI.parse 'redis://localhost/:6379/0/cache' # => #<URI::Generic redis://localhost/:6379/0/cache>
uri.port # => nil
uri.path # => "/:6379/0/cache"
uri.host # => "localhost"
```

Notice how the URI library is having trouble parsing out the port? I believe that might have something to do with this. Make sure the String you're passing in doesn't have that extra slash between the host and port...

```ruby
uri = URI.parse 'redis://localhost:6379/0/cache' # => #<URI::Generic redis://localhost:6379/0/cache>
uri.host # => "localhost"
uri.port # => 6379
uri.path # => "/0/cache"
```

**Comment by nitvik** [comment]
Ah! 
I understand the problem now. Thanks.

**Comment by tubbo** [comment]
No problem!
