### ISSUE TITLE
Setting on Rails 5.1.3

### ISSUE THREAD

**Issue by ulisescarreonalvarez** [redis-store/redis-rails#76]
Hi, i'm making a simple aplication
i created a redis instance on AWS, i cant connect without problem on Python and another languages,
i'm new on Rails so basically i set up the gem and on my "config/application.rb" i have:

```
require_relative 'boot'

require 'rails/all'

Bundler.require(*Rails.groups)

module Gasideal
  class Application < Rails::Application
    config.load_defaults 5.1
    config.session_store = :redis_store, {
        host: "my_host",
        port: 6379,
        db: 0,
        password: "my_pass",
        namespace: "my_namespace"
    }
    config.to_prepare do
        Devise::SessionsController.layout "devise"
        Devise::RegistrationsController.layout "devise_up"
        Devise::ConfirmationsController.layout "devise_co"
        Devise::UnlocksController.layout "devise_un"
        Devise::PasswordsController.layout "devise_pass"      
    end
  end
end
```

The app run without problem, but if i change the url or something of the config the app don't throw an alert or exception, how can i know if the session store on redis are working o what am i missing on the configuration?

Regards!

**Comment by tubbo** [comment]
When you make changes in the config/ directory, you must restart your app server for changes to take effect. Did you restart your server after making the change?

- T

**Comment by ulisescarreonalvarez** [comment]
Yes i restarted the application but when i change the settings i don't see a timeout or something like that, i want to know if the app really uses the redis for the session storage.

**Comment by tubbo** [comment]
@ulisescarreonalvarez you might have to actually try to run a command on the Redis server to see that happen, because the client doesn't open a connection immediately I don't believe.

**Comment by ulisescarreonalvarez** [comment]
@tubbo Hi i solved in the most dumb way possible, actually i have the application over a VPC with private IPs the problem was that certain subnet doesn't have permissions to connect to redis, but if ruby-store doesn't connect might be throw an error?

Regards and thanks.

**Comment by tubbo** [comment]
@ulisescarreonalvarez hey i'm gonna close this if it's a problem dependent on outside config...I thought the `Redis::Store` would error out if it can't connect to Redis.
