### ISSUE TITLE
Rails adding extra line in my redis cache

### ISSUE THREAD

**Issue by joao-alberto** [redis-store/redis-rails#82]
Im using redis-rails in my project to store a cache of users, and I don't know why a extra line is added at begining of cache. (Line 1 "o: ActiveSupport::Cache::Entry:@valueI"�")

![z1qmy](https://user-images.githubusercontent.com/10820159/36791934-d982d244-1c77-11e8-8ab2-96659ebb1e58.png)

Config:
```
config.cache_store = :redis_store, {
  host: ENV['REDIS_SERVER'] || 'localhost',
  port: 6379,
  db: 0,
  namespace: ENV['CUSTOMER']
}
```

Code:
```
  namespace :update_personas_cache do
    desc "Update personas cache"
    task update: :environment do
      personas = []

      Persona.joins(:employee).where(employees: { active: true }).each do |persona|
        personas.push({id: persona.id, name: persona.name})
      end

      Rails.cache.write "personas", personas.to_json
    end
  end
```

**Comment by tubbo** [comment]
`ActiveSupport::Cache::Entry` is the object that Rails wraps your cached data in to be marshalled and stored in the database. It's not in use as of v4.x and above.

**Comment by joao-alberto** [comment]
@tubbo Thanks for the quick response.

But Im using `rails 4.2.6` and `redis-rails 5.0.2` and this keeps happening. I need to set a specific config?

**Comment by tubbo** [comment]
@joao-alberto Sorry, I was mistaken...just that I didn't see it in the docs after 4.0, but `ActiveSupport::Cache::Entry` still exists in the source. At any rate, it's nothing to worry about...it's just how Rails stores its data. [Here's some more information about what AS::Cache::Entry does](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/cache.rb#L702-L709)

**Comment by joao-alberto** [comment]
@tubbo Got it. Thanks man!

Then I need to find another way to avoid my problem when fetch this with my node js api

**Comment by tubbo** [comment]
@joao-alberto unfortunately, it seems [cache entries are not guaranteed to be portable](https://github.com/rails/rails/issues/17923#issuecomment-65719347) between stacks.

**Comment by joao-alberto** [comment]
@tubbo I will try soon, thanks for your support. 🤘
