### ISSUE TITLE
Does it work with cache_version enabled in Rails 5.2?

### ISSUE THREAD

**Issue by Hirurg103** [redis-store/redis-rails#94]
After I upgraded to Rails 5.2 I started getting this deprecation warning:

```
DEPRECATION WARNING: Specifying a timestamp name for #cache_key has been deprecated
in favor of the explicit #cache_version method that can be overwritten.
```

I investigated it a bit and found out that Rails 5.2 introduced [versioned cache store](https://guides.rubyonrails.org/5_2_release_notes.html#active-record-notable-changes) (See 7th item in the list)

Also they added [redis cache store](https://guides.rubyonrails.org/caching_with_rails.html#activesupport-cache-rediscachestore) which supports cache versioning

I am going to enable cache versioning with 

```
config.active_record.cache_versioning = true
```

For now I am using `:redis_store` as a cache store.

Does it support cache versioning or it will be better to switch to `:redis_cache_store`?

**Comment by tubbo** [comment]
It would be better to switch to `:redis_cache_store` in this case, as [redis-activesupport](https://github.com/redis-store/redis-activesupport) doesn't support versioned cache keys. Additionally, there's better support for alternative drives (like `hiredis`).

**Comment by Hirurg103** [comment]
Hi @tubbo , thank you!
